
/vis/viewer/set/viewpointVector 1 0 0
/vis/viewer/zoom 1.4
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# use KeepThisEvent in source code
/vis/scene/endOfEventAction accumulate
# 
#/vis/viewer/set/autoRefresh true

/vis/disable


## beamOn
## /vis/enable
## /vis/drawOnlyToBeKeptEvents
## /vis/viewer/rebuild
